Django/Django_Project_Tutorial/poll_project/poll_app/urls.py
from django.urls import path
from . import views

app_name = 'poll_app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/',views.DetailView.as_view(), name = 'detail'),
    path('<int:pk>/results/',views.ResultsView.as_view(), name = 'results'),
    path('<int:question_id>/vote/',views.vote, name = 'vote'),
]

Django/Django_Project_Tutorial/poll_project/poll_project/urls.py
from django.contrib import admin
from django.urls import path,include
from poll_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll_app/', include('poll_app.urls')),
]

Django/Django_Project_Tutorial/poll_project/poll_app/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    que_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('published date')

    def __str__(self):
        return self.que_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

Django/Django_Project_Tutorial/poll_project/poll_app/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseRedirect
from .models import Question,Choice
from django.urls import reverse
from django.views import generic
from django.utils import timezone

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'poll_app/index.html'
    context_object_name = 'latest_que_list'

    def get_queryset(self):
        """Return the last five published questions (not including those set to be
        published in the future)."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'poll_app/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'poll_app/results.html'

def vote(request,question_id):
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        return render(request, "poll_app/detail.html", {'question':question, 'error_message':"You didn't select a choice."})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('poll_app:results',args=(question.id,)))
    return HttpResponse("Vote for question %s" % question_id)


##############################################################################################################################################
# default DetailView name = <app name>/<model name>_detail.html           "poll_app/question_detail.html"
# default ListView name = <app name>/<model name>_list.html               "poll_app/question_list.html"
# DetailView context variable name = <model_name> with lowercase          "question"
# ListView context variable name = <model_name>_list                      "question_list"
# To override this variables default name we have used template_name, context_object_name parameters
###############################################################################################################################################

# def index(request):
#     latest_que_list = Question.objects.order_by('-pub_date')[:5]
#     return render(request, 'poll_app/index.html', { 'latest_que_list' : latest_que_list }   )
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id )
#     return render(request, "poll_app/detail.html", { 'question' : question })
#
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id )
#     return render(request, "poll_app/results.html", {"question" : question} )

Django/Django_Project_Tutorial/poll_project/poll_app/templates/poll_app/detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Details Page</title>
  </head>
  <body>
    <div class="container">


      <h1>{{question.que_text}}</h1>
      {% if error_message %}
        <p> <strong> {{error_message}}</strong> </p>
      {% endif %}

      <form action="{% url 'poll_app:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
          <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
          <label for="choice{{forloop.counter}}"> {{choice.choice_text}} </label>
          <br>
        {% endfor %}

        <input type="submit" class="btn btn-primary" value="Vote">
      </form>



    </div>
  </body>
</html>

Django/Django_Project_Tutorial/poll_project/poll_app/templates/poll_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'poll_app/style.css'%}">
    <title>Home Page</title>
  </head>
  <body>
    <div class="container">

      {% if latest_que_list %}
        <ul>
          {% for que in latest_que_list %}
            <br> <li> <a href="{% url 'poll_app:detail' que.id %}"> {{que.que_text}} </a> </li> <br>
            <!-- NEVER PUT SPACE BETWEEN "poll_app:detail" -->
          {% endfor %}
        </ul>

      {% else %}
        <h3>No polls are available</h3>
      {% endif %}
    </div>

  </body>
</html>

<!-- <li> <a href="/poll_app/{{que.id}}"> {{que.que_text}} </a> </li> -->

Django/Django_Project_Tutorial/poll_project/poll_app/templates/poll_app/results.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Results</title>
  </head>
  <body>
    <div class="container">

      <h1>{{question.que_text}}</h1>
      <ul>
        {% for choice in question.choice_set.all %}
          <li>{{choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
          <!-- pluralize : 1vote and 2votes -->
        {% endfor %}
      </ul>

      <a href="{% url 'poll_app:detail' question.id %}"> <button type="button" class="btn btn-primary" name="button">Vote Again</button> </a>
      <a href="{% url 'poll_app:index' %}"> <button type="button" class="btn btn-primary" name="button">Go To Home</button></a>

    </div>
  </body>
</html>